@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package lehjr.numina.common.capabilities.energy;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;