
["ChargingBase settings"]
	#Max base power for charging base
	#Range: 100 ~ 10000000
	chargingBaseMaxEnergy = 1000000
	#Max power transfer for charging base
	#Range: 10 ~ 1000000
	chargingBaseMaxTransfer = 10000

[Batteries]

	[Batteries.battery_basic]
		#Range: > 0
		maxEnergy = 1000000
		#Range: > 0
		maxEnergyTransfer = 1250000
		isAllowed = true

	[Batteries.battery_advanced]
		#Range: > 0
		maxEnergy = 1000000
		#Range: > 0
		maxEnergyTransfer = 1250000
		isAllowed = true

	[Batteries.battery_elite]
		#Range: > 0
		maxEnergy = 1000000
		#Range: > 0
		maxEnergyTransfer = 1250000
		isAllowed = true

	[Batteries.battery_ultimate]
		#Range: > 0
		maxEnergy = 1000000
		#Range: > 0
		maxEnergyTransfer = 1250000
		isAllowed = true

