@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package numina.common.recipes;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;