@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package powersuits.common.recipes;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;