@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package lehjr.powersuits.common.item.module.environmental;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;