modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/lehjr/MachineMusePowersuits/issues"
license="${mod_license}"

[[mods]]
    modId="${mod_license}"
    version="${mod_version}"
    displayName="${mod_name}"
    displayURL="https://github.com/lehjr/MachineMusePowersuits"
    authors="${mod_authors}"
    description='''${mod_description}'''

[[accessTransformers]]
    file="META-INF/accesstransformer.cfg"

[[mixins]]
    config="numina.mixins.json"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
