modLoader="javafml"
loaderVersion="${loader_version}"
issueTrackerURL="https://github.com/lehjr/MachineMusePowersuits/issues"
license="All rights reserved"
[[mods]]
    modId="mpsrecipecreator"
    version="${version}"
    displayName="MPS-RecipeCreator"
    #updateJSONURL="?"
    displayURL="https://github.com/lehjr/MachineMusePowersuits"
    authors="lehjr"
    description="A really bad mod for creating recipes for Modular Powersuits"

[[dependencies.mpsrecipecreator]]
    modId="forge"
    mandatory=true
    versionRange="${neo_version}"
    side="BOTH"

[[dependencies.mpsrecipecreator]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version}"
    side="BOTH"

[[dependencies.mpsrecipecreator]]
    modId="numina"
    mandatory=true
    versionRange="[${version},)"
    ordering="AFTER"
    side="BOTH"
