@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package lehjr.numina.common.capabilities.module.powermodule;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;