@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package lehjr.numina.common.capabilities.render.chameleon;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;