@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package lehjr.numina.common.capability.inventory.modechanging;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;