@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package lehjr.numina.common.capabilities.player.keystates;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;