modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/lehjr/MachineMusePowersuits/issues"
license="All rights reserved"
[[mods]]
    modId="mpswhatever"
    version="${version}"
    displayName="MPS-Whatever"
    #updateJSONURL="http://myurl.me/"
    displayURL="https://github.com/lehjr/Numina"
    authors="lehjr"
    description="A random assortment of... uh... stuff."

# The [[mixins]] block allows you to declare your mixin config to FML so that it gets loaded.
#[[mixins]]
#config="mpswhatever.mixins.json"

# The [[accessTransformers]] block allows you to declare where your AT file is.
# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
[[accessTransformers]]
    file="META-INF/accesstransformer.cfg"

[[dependencies.mpswhatever]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version}"
    side="BOTH"

[[dependencies.mpswhatever]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version}"
    side="BOTH"

[[dependencies.mpswhatever]]
    modId="powersuits"
    type="required"
    versionRange="[${version},)"
    side="BOTH"

[[dependencies.mpswhatever]]
    modId="numina"
    type="required"
    versionRange="[${version},)"
    side="BOTH"
